name: "node.js check"
on: [push]
jobs:
  is-my-node-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
      - name: Run
        run: npx is-my-node-vulnerable

  is-my-dep-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
      - name: Run
        run: npm audit
